# Generated by Django 4.2.19 on 2025-02-21 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cardcontrol", "0005_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Card",
        ),
    ]
