# Generated by Django 4.2.11 on 2025-02-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardcontrol", "0007_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="card_account",
            field=models.CharField(max_length=255, verbose_name="Card Number"),
        ),
        migrations.AlterField(
            model_name="card",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="end_date"),
        ),
    ]
