# Generated by Django 4.2.11 on 2025-02-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cardcontrol", "0008_alter_card_card_account_alter_card_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="is_active",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
